# Site settings
# Ref: http://jekyllrb.com/docs/github-pages/#project-page-url-structure

title: Codey
email: hello@pencilcasestudios.com
description: "A different take on the WordPress Codex"
baseurl: "/codey" # the subpath of your site, e.g. /blog/
url: "http://pencilcasestudios.github.io" # the base hostname & protocol for your site
twitter_username: pencilcasestudi
github_username:  pencilcasestudios

# Build settings
markdown: kramdown
